#############################################################################
# Makefile for building: fontpro
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 4? 5 10:19:50 2017
# Project:  fontpro.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile fontpro.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iinclude -Iinclude/freetype -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L./include/lib -lft -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		fontconvert.cpp \
		characterset.cpp \
		posix_qextserialport.cpp \
		qextserialbase.cpp \
		qextserialport.cpp \
		stm32flash.cpp \
		printerft.cpp \
		charset_convert.cpp moc_fontconvert.cpp \
		moc_qextserialbase.cpp \
		moc_qextserialport.cpp \
		moc_stm32flash.cpp \
		moc_printerft.cpp \
		moc_charset_convert.cpp
OBJECTS       = main.o \
		fontconvert.o \
		characterset.o \
		posix_qextserialport.o \
		qextserialbase.o \
		qextserialport.o \
		stm32flash.o \
		printerft.o \
		charset_convert.o \
		moc_fontconvert.o \
		moc_qextserialbase.o \
		moc_qextserialport.o \
		moc_stm32flash.o \
		moc_printerft.o \
		moc_charset_convert.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		fontpro.pro
QMAKE_TARGET  = fontpro
DESTDIR       = 
TARGET        = fontpro

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_fontwidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: fontpro.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile fontpro.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile fontpro.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/fontpro1.0.0 || $(MKDIR) .tmp/fontpro1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/fontpro1.0.0/ && $(COPY_FILE) --parents fontconvert.h gb18030_unicode_table.h common.h characterset.h posix_qextserialport.h qextserialbase.h qextserialport.h stm32flash.h printerft.h charset_convert.h .tmp/fontpro1.0.0/ && $(COPY_FILE) --parents main.cpp fontconvert.cpp characterset.cpp posix_qextserialport.cpp qextserialbase.cpp qextserialport.cpp stm32flash.cpp printerft.cpp charset_convert.cpp .tmp/fontpro1.0.0/ && $(COPY_FILE) --parents fontwidget.ui .tmp/fontpro1.0.0/ && (cd `dirname .tmp/fontpro1.0.0` && $(TAR) fontpro1.0.0.tar fontpro1.0.0 && $(COMPRESS) fontpro1.0.0.tar) && $(MOVE) `dirname .tmp/fontpro1.0.0`/fontpro1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/fontpro1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_fontconvert.cpp moc_qextserialbase.cpp moc_qextserialport.cpp moc_stm32flash.cpp moc_printerft.cpp moc_charset_convert.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_fontconvert.cpp moc_qextserialbase.cpp moc_qextserialport.cpp moc_stm32flash.cpp moc_printerft.cpp moc_charset_convert.cpp
moc_fontconvert.cpp: ui_fontwidget.h \
		common.h \
		characterset.h \
		qextserialport.h \
		posix_qextserialport.h \
		qextserialbase.h \
		stm32flash.h \
		charset_convert.h \
		printerft.h \
		fontconvert.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) fontconvert.h -o moc_fontconvert.cpp

moc_qextserialbase.cpp: qextserialbase.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) qextserialbase.h -o moc_qextserialbase.cpp

moc_qextserialport.cpp: posix_qextserialport.h \
		qextserialbase.h \
		qextserialport.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) qextserialport.h -o moc_qextserialport.cpp

moc_stm32flash.cpp: qextserialport.h \
		posix_qextserialport.h \
		qextserialbase.h \
		stm32flash.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) stm32flash.h -o moc_stm32flash.cpp

moc_printerft.cpp: qextserialport.h \
		posix_qextserialport.h \
		qextserialbase.h \
		printerft.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) printerft.h -o moc_printerft.cpp

moc_charset_convert.cpp: characterset.h \
		common.h \
		charset_convert.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) charset_convert.h -o moc_charset_convert.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_fontwidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_fontwidget.h
ui_fontwidget.h: fontwidget.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic fontwidget.ui -o ui_fontwidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp fontconvert.h \
		ui_fontwidget.h \
		common.h \
		characterset.h \
		qextserialport.h \
		posix_qextserialport.h \
		qextserialbase.h \
		stm32flash.h \
		charset_convert.h \
		printerft.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

fontconvert.o: fontconvert.cpp fontconvert.h \
		ui_fontwidget.h \
		common.h \
		characterset.h \
		qextserialport.h \
		posix_qextserialport.h \
		qextserialbase.h \
		stm32flash.h \
		charset_convert.h \
		printerft.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fontconvert.o fontconvert.cpp

characterset.o: characterset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o characterset.o characterset.cpp

posix_qextserialport.o: posix_qextserialport.cpp posix_qextserialport.h \
		qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o posix_qextserialport.o posix_qextserialport.cpp

qextserialbase.o: qextserialbase.cpp qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialbase.o qextserialbase.cpp

qextserialport.o: qextserialport.cpp qextserialport.h \
		posix_qextserialport.h \
		qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialport.o qextserialport.cpp

stm32flash.o: stm32flash.cpp stm32flash.h \
		qextserialport.h \
		posix_qextserialport.h \
		qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stm32flash.o stm32flash.cpp

printerft.o: printerft.cpp printerft.h \
		qextserialport.h \
		posix_qextserialport.h \
		qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o printerft.o printerft.cpp

charset_convert.o: charset_convert.cpp charset_convert.h \
		characterset.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o charset_convert.o charset_convert.cpp

moc_fontconvert.o: moc_fontconvert.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fontconvert.o moc_fontconvert.cpp

moc_qextserialbase.o: moc_qextserialbase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qextserialbase.o moc_qextserialbase.cpp

moc_qextserialport.o: moc_qextserialport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qextserialport.o moc_qextserialport.cpp

moc_stm32flash.o: moc_stm32flash.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stm32flash.o moc_stm32flash.cpp

moc_printerft.o: moc_printerft.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_printerft.o moc_printerft.cpp

moc_charset_convert.o: moc_charset_convert.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_charset_convert.o moc_charset_convert.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

